kind: ServiceAccount
apiVersion: v1
metadata:
  name: daskkubernetes
  namespace: jupyter

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: daskkubernetes
  namespace: jupyter
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: daskkubernetes
  namespace: jupyter
subjects:
- kind: ServiceAccount
  name: daskkubernetes
roleRef:
  kind: Role
  name: daskkubernetes
  apiGroup: rbac.authorization.k8s.io
