# TOKEN should be output from `openssl rand -hex 32`
proxy:
  secretToken: "TOKEN"

# GitHub Auth
#auth:
#  type: github
#  github:
#    clientId: "CLIENTID"
#    clientSecret: "SECRET"
#    callbackUrl: "http://your.domain.org/hub/oauth_callback"
#  admin:
#    access: true
#    users:
#      - github_username1
